(define (main)
        (setPort (open (getElement ScamArgs 1) 'read))
        (apply pt (readExpr))
)
(define (pt n)
	(define (numPrint row col)
		(cond
			;((or(> row col) (!= row col)) println(pas row col))
			((or (> row col) (= row col)) (print (pas row col) ))
			;((= row 0) (print "\n") )
			;((or (> row col) (= row col)) (print (pas row col) ))
			;((= row ) (print "1"))
			;(else (return))
		)
		(if (!= row col) (spacePrint 1))
		(if (> row col) (numPrint row (+ col 1)))
	)
	(define (linePrint row)
		(if(< row n)
			(begin
				(spacePrint (- n (+ row 1)) )
				(numPrint row 0)
				(print "\n")
				(linePrint (+ row 1))
			)
		)
	)
	(define (spacePrint row)
		(if(> row 0) (print " "))
		(if(> row 0) (spacePrint (- row 1)) )
	)
	(define (pas row col) 
		(cond
    		((or (= 0 col) (= row col)) 1)
       		(else (+ (pas (- row 1) col)
                 (pas (- row 1) (- col 1))))
       	)
	)
	(linePrint 0)
)