(include "pretty.lib")
(define (cache func)
  (define denv (get '__context func))
  (define body (cdr (get 'code func)))
  (define local (get 'parameters func))
  (define (function? items)
    (and (eq? (car items) 'define)
         (list? (car (cdr items)))))
  (define (define? items)
    (eq? (car items) 'define))
  (define (lambda? items)
    (eq? (car items) 'lambda))
  (define (let? items)
    (eq? (car items) 'let))
  (define (remove-non-local items)
    (cond
      ((null? items) 'DONE)
      ((atom? (car items)) 
        (if (not (member? (car items) local))
            (set-car! items (get (car items) denv))
        )
        (remove-non-local (cdr items))
      )
      ((list? (car items))
       (if (define? (car items))
          (begin (set-car! (car items) (get (car (car items)) denv))
            (if (atom? (car (cdr (car items))))
                (set! local (cons (car (cdr (car items))) local))
                (set! local (cons (car (car (cdr (car items) ) ) ) local) )
            )
          )
          (if (not (or (lambda? (car items)) (let? (car items))))
            (remove-non-local (car items))
          )
        )
       (remove-non-local (cdr items))
      )
      (else (error "Unknown type")
      )
    )
  )
  (remove-non-local body)
)
(define (main)
  (define (square x) (multiply x x))
  (define (multiply a b) (* a b))
  (cache square)
  (pretty square)
  (pretty multiply)
)